version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@1.4.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: arm.large
    steps:
      - checkout
      - aws-cli/setup
      - run: echo "hollla!"
      - node/install:
         node-version: 16.20.0
