version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: arm.large
    steps:
      - checkout
      - run: echo "hollla!"
      - node/install:
         node-version: 16.20.0
