version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2-browsers
    steps:
      - checkout
      - run: echo "hollla!"
      - run:
          name: Change apt repository to mirror
          command: sudo sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirror.enzu.com/ubuntu/|g' /etc/apt/sources.list
      - run:
          name: Change apt repository to mirror
          command: sudo apt-get update
      - node/install:
          node-version: '18.15.0'
