version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2-browsers
    steps:
      - checkout
      - run: echo "hollla!"
      - node/install:
         node-version: '18.15.0'
